enum Category {
  DOCUMENT,
  LIBITEM,
  USER,
  WINDOWS,
  EMAIL,
  AUTRE
}

type Function @Collection(name: "Function") {
  name : String!,
  description : String!,
  code : String!,
  category: Category!
}

type Query {
  allFunctions: [Function!]! @index(name: "all_functions")
}

type Mutation {
  addFunction(): Function! @resolver(name: "add_function")
}